name: FlareSolverr Integration

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-flaresolverr:
    runs-on: ubuntu-latest
    
    services:
      # 启动 FlareSolverr 作为后台服务
      flaresolverr:
        image: ghcr.io/flaresolverr/flaresolverr:latest
        ports:
          - 8191:8191
        env:
          LOG_LEVEL: info
        options: >-
          --health-cmd "curl -f http://localhost:8191/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run test script using FlareSolverr
      env:
        FLARESOLVERR_URL: http://localhost:8191
      run: |
        python FlareSolverr.py

    env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}